version: '3.6'
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/private/localhost.key:/etc/ssl/private/localhost.key
      - /etc/ssl/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx_config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - wg-portal

  wg-portal:
    image: h44z/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    expose: # 
      - '8123'
    environment:
      # WireGuard Settings
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      # Core Settings
#      - EXTERNAL_URL=https://vpn.company.com
      - WEBSITE_TITLE=WireGuard VPN
      - COMPANY_NAME=change_me
      - ADMIN_USER=test@domain.com
      - ADMIN_PASS=change_me
      # Mail Settings
#      - MAIL_FROM=WireGuard VPN <noreply+wireguard@company.com>
#      - EMAIL_HOST=10.0.0.1
#      - EMAIL_PORT=25
      # LDAP Settings
#      - LDAP_ENABLED=flase
#      - LDAP_URL=ldap://srv-ad01.company.local:389
#      - LDAP_BASEDN=DC=COMPANY,DC=LOCAL
#      - LDAP_USER=ldap_wireguard@company.local
#      - LDAP_PASSWORD=supersecretldappassword
#      - LDAP_ADMIN_GROUP=CN=WireGuardAdmins,OU=Users,DC=COMPANY,DC=LOCAL
